sudo: required
dist: trusty
language: generic
install:
  - export CI_ROS_DISTRO=indigo
  - echo $CI_ROS_DISTRO
# Add ROS repositories
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update
# Install and initialize rosdep
  - sudo apt-get install python-rosdep python-catkin-pkg -y
  - sudo `which rosdep` init
  - rosdep update
# Use rosdep to install rostful-node's dependencies
  - rosdep install --default-yes --from-paths ./ --rosdistro $CI_ROS_DISTRO
script:
  - mkdir build && cd build
  - source /opt/ros/$CI_ROS_DISTRO/setup.bash && cmake .. -DCMAKE_INSTALL_PREFIX=./install
  - source devel/setup.bash && make -j1 run_tests && catkin_test_results . && make -j1 install
notifications:
  email: false
